### ISSUE TITLE
Any of ipcbench utilities except for "pipe" fails running via sudo

### ISSUE THREAD

**Issue by betulum** [goldsborough/ipc-bench#16]
sudo shm/shm returns:
Could not set group id for child process: Operation not permitted
Could not set group id for child process: Operation not permitted

**Comment by ValiValpas** [comment]
@betulum I was getting the same error when executing `shm` from a bash script. My workaround is using `setsid shm`.

**Comment by ess476** [comment]
The bash script is not running in interactive mode causing the `setpgid` to fail (as there's no underling tty or something). Make sure you're doing `#!/bin/bash -i`

**Comment by alexandervanrenen** [comment]
Good catch!

Fixed the shebang in the supplied scripts.
